version: '2'
catalog:
  name: "MySQL Asynchrouns Replication"
  version: "v0.1"
  description: "MySQL Asynchronous replication"
services:
  slave:
    retain_ip: true
    scale: 1
    start_on_create: true
  master-sidekick:
    retain_ip: true
    scale: 1
    start_on_create: true
  slave-sidekick:
    retain_ip: true
    scale: 1
    start_on_create: true
  master:
    retain_ip: true
    scale: 1
    start_on_create: true
  mysql-lb:
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - priority: 1
        protocol: tcp
        service: master
        source_port: 3306
        target_port: 3306
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000