version: '2'
services:
  slave:
    retain_ip: true
    scale: 1
    start_on_create: true
  master-sidekick:
    retain_ip: true
    scale: 1
    start_on_create: true
  slave-sidekick:
    retain_ip: true
    scale: 1
    start_on_create: true
  master:
    retain_ip: true
    scale: 1
    start_on_create: true